# ── Conversation States ──

# Add account
SELECT_ADD_TYPE = 1
WAIT_SINGLE_SESSION = 2
WAIT_BULK_COUNT = 3
WAIT_BULK_SESSION = 4

# Join
WAIT_JOIN_LINK = 5
WAIT_JOIN_COUNT = 6
WAIT_JOIN_TIMING = 7

# Mode
WAIT_MODE_COUNTS = 8

# Reaction
WAIT_REACTION_LINK = 9
WAIT_REACTION_COUNT = 10
WAIT_REACTION_EMOJI = 11

# Views
WAIT_VIEWS_LINKS = 12
WAIT_VIEWS_COUNT = 13

# Remove
WAIT_REMOVE_CHAT = 14
