# ── Add Account ──
WAIT_SINGLE_SESSION = 10
WAIT_BULK_COUNT = 11
WAIT_BULK_SESSION = 12

# ── Join ──
WAIT_JOIN_LINK = 20
WAIT_JOIN_COUNT = 21
WAIT_JOIN_TIMING = 22

# ── Mode ──
WAIT_MODE_COUNTS = 30

# ── Reaction ──
WAIT_REACTION_LINK = 40
WAIT_REACTION_COUNT = 41
WAIT_REACTION_EMOJI = 42

# ── Views ──
WAIT_VIEWS_LINKS = 50
WAIT_VIEWS_COUNT = 51

# ── Remove ──
WAIT_REMOVE_CHAT = 60
